# rename this file to config.yaml before start

# qqbot account, not needed anymore for qrcode authentication
account:  2353783363
password: "123456"

# server to view verification code, not required for mac
port: 3100
host: localhost

# message handling, ignore offline message 20 min ago
# offline_msg_keeptime: 1200

# plugin list
plugins:
    - help
    - debug
    - apiserver
    - post-discourse

# apiserver plugin configration
api_port:  3200
api_token: ''

discourse:
    url: 'you_site_url'
    api_key: 'your_key'
    api_username: 'your_username'
    post_category: 'your_id'